name: Deploy

on:
  push:
    branches-ignore:
      - 'dependabot/**'

jobs:
  # prepare:
  #   runs-on: ubuntu-latest
  #   name: Preparing environment
  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 0
      
  #     - name: Retrieving base and head references
  #       shell: bash
  #       id: branch
  #       run:  |
  #         echo "::set-output name=HEAD::${{ github.sha }}"
  #         if [[ $GITHUB_BASE_REF ]]
  #         then
  #           echo "::set-output name=BRANCH_REF::${GITHUB_HEAD_REF}"
  #         else
  #           echo "::set-output name=BRANCH_REF::${GITHUB_REF#refs/heads/}~1"
  #         fi
  #     - name: Detect changed directories
  #       uses: gagle/nx-check-changes@v1.0.0
  #       id: nx-changes
  #       with:
  #         baseRef: ${{ steps.branch.outputs.BRANCH_REF }}
  #         headRef: ${{ steps.branch.outputs.HEAD }}

  #     - uses: actions/cache@v2
  #       id: npm-cache
  #       with:
  #         path: '**/node_modules'
  #         key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

  #     - name: Install Dependencies
  #       if: steps.npm-cache.outputs.cache-hit != 'true' && steps.nx-changes.outputs.not-affected == 'false'
  #       run: npm install
         
  #     - name: Parsing affected applications
  #       id: parser
  #       run: | 
  #         echo "::set-output name=affected::[$(echo ${{ steps.nx-changes.outputs.changed-dirs }} | sed "s/[^ ][^ ]*/\"&\"/g" | sed 's/ /, /g')]"
          
  #   outputs:
  #     affected: ${{ steps.parser.outputs.affected }}
  #     skip: ${{ steps.nx-changes.outputs.not-affected }}

  deploy:
    # if: needs.prepare.outputs.skip == 'false'
    runs-on: ubuntu-latest
    # needs: [prepare]
      
    # strategy:
    #   matrix: 
    #     affected: ${{ fromJson(needs.prepare.outputs.affected) }}
    steps:
      - uses: actions/checkout@v2
        # if: contains(matrix.affected, 'application-1')
      - name: Deploy Backoffice Producer
        uses: actions/vercel-deployment@0.5.3
        with:
          vercelToken: ${{ secrets.VERCEL_TOKEN }}
          vercelOrgId: ${{ secrets.VERCEL_ORG_ID }}
          vercelProjectId: ${{ secrets.VERCEL_PROJECT_ID }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}

  #     # - name: Deploy Backoffice Staff
  #     #   if: contains(matrix.affected, 'application-2')
  #     #   uses: amondnet/vercel-action@v20
  #     #   with:
  #     #     vercel-token: ${{ secrets.VERCEL_TOKEN }}
  #     #     github-token: ${{ secrets.GITHUB_TOKEN }} 
  #     #     vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
  #     #     vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID_APP_2 }} 
  #     #     vercel-args: '--prod'
  #         # alias-domains: |
  #         #   *.application2-vitorcamacho.app
  #         #   {{BRANCH}}.application2-vitorcamacho.app