name: Deploy

on:
  push:
    branches-ignore:
      - 'dependabot/**'

env:
  BEFORE_SHA: ${{ github.event.before }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  VERCEL_ORG_ID: ${{ secrets.ORG_ID}}
  BACKOFFICE_STAFF_PROJECT_ID: ${{ secrets.BACK_OFFICE_STAFF_PROJECT_ID}}
  BACKOFFICE_PRODUCER_PROJECT_ID: ${{ secrets.BACK_OFFICE_PRODUCER_PROJECT_ID}}

jobs:
  deploy:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Use Node.js 15
        uses: actions/setup-node@v1
        with:
          node-version: 15.x

      - name: Install dependencies
        run: npm install

      - name: Fetch other branches
        run: git fetch --no-tags --prune --depth=5 origin $GITHUB_BASE_REF

      - uses: mansagroup/nrwl-nx-action@v1
        with:
          targets: deploy

      # - name: Deploy affected applications
      #   run: npm run affected:deploy -- --parallel --base=$BEFORE_SHA
      #   shell: bash
