name: Deploy

on:
  push:
    branches-ignore:
      - 'dependabot/**'      
jobs:
  deploy:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Use Node.js 15
        uses: actions/setup-node@v1
        with:
          node-version: 15.x

      - uses: actions/cache@v2
        id: npm-cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install Dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm install

      - name: Deploy affected applications
        run: npm run affected:deploy -- --parallel --base=${{ github.event.before }}      
        shell: bash
    
      - uses: emregency/vercel-preview-alias@v1.5
        with:
          # more about GitHub secrets https://docs.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          vercel-preview-url: ${{ github.event.deployment_status.target_url }} #Required
          vercel-target-url: https://test-deploy-nwrl-workspace.vercel.app #Required
          