name: Deploy

on:
  push:
    branches-ignore:
      - 'dependabot/**'

env:
  VERCEL_TOKEN: YN9Wo93V7aLRTOjBPCpw1eKs
  VERCEL_ORG_ID: nI8rwi0PrCS4dtjLugZQt3pg
  VERCEL_PROJECT_ID: prj_0QH3ZK4h12TpTnDSOgNvpoZCzYmz
      
jobs:
  deploy:
    # if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest

    steps:
      # - uses: actions/checkout@v2
      #   with:
      #     ref: ${{ github.event.pull_request.head.ref }}
      #     fetch-depth: 0

      # - name: Use Node.js 15
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: 15.x

      # - uses: actions/cache@v2
      #   id: npm-cache
      #   with:
      #     path: '**/node_modules'
      #     key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      # - name: Install Dependencies
      #   if: steps.npm-cache.outputs.cache-hit != 'true'
      #   run: npm install

      - name: Deploy affected applications
        run: npm run affected:deploy -- --parallel --base=${{ github.event.before }}      
        shell: bash
       
      - name: vercel-preview-url
        uses: zentered/vercel-preview-url@v1.0.0
        id: vercel_preview_url
        env:
          VERCEL_TOKEN: ${{ env.VERCEL_TOKEN }}
        with:
          vercel_team_id:  ${{ env.VERCEL_ORG_ID }}
          vercel_project_id:  ${{ env.VERCEL_PROJECT_ID }}
      - name: Get URL
        run: echo "https://${{ steps.vercel_preview_url.outputs.preview_url }}"