name: Deploy

on:
  push:
    branches-ignore:
      - 'dependabot/**'

jobs:
  install:
    runs-on: ubuntu-latest
    name: Installing Dependencies
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@master
      - name: Finish
        run: echo Finish
  # deploy:
  #   # if: "!contains(github.event.head_commit.message, '[skip ci]')"
  #   runs-on: ubuntu-latest

  #   steps:
  #     # - uses: actions/checkout@v2
  #     #   with:
  #     #     ref: ${{ github.event.pull_request.head.ref }}
  #     #     fetch-depth: 0

  #     # - name: Use Node.js 15
  #     #   uses: actions/setup-node@v1
  #     #   with:
  #     #     node-version: 15.x

  #     # - uses: actions/cache@v2
  #     #   id: npm-cache
  #     #   with:
  #     #     path: '**/node_modules'
  #     #     key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

  #     # - name: Install Dependencies
  #     #   if: steps.npm-cache.outputs.cache-hit != 'true'
  #     #   run: npm install

  #     - name: Deploy affected applications
  #       run: |
  #         echo "::set-output name=OUTPUT_COMMAND::$(npm run affected:deploy -- --parallel --base=${{ github.event.before }})"
  #       shell: bash
  #       id: deploy
  #       env:
  #         VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  #         VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID}}
  #         VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID}}

  #     - name: print output
  #       shell: bash
  #       run: | 
  #         echo BEGIN \n
  #         echo ${{ steps.deploy.outputs.OUTPUT_COMMAND }}
  #         echo END \n